#!/usr/bin/env python3
"""Compare public Agent Server output against a fixed official service.

This command starts no services. Start a pinned ``langgraph dev`` reference and
``graphharbor serve`` with the same configuration, then pass their base URLs.
Only UUIDs, timestamps, and generated service locations are normalized.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.error import HTTPError
from urllib.request import Request, urlopen

DEFAULT_PROBES = ("GET:/ok", "GET:/info", "GET:/openapi.json")
_DYNAMIC_KEYS = frozenset({"created_at", "updated_at", "state_updated_at", "timestamp"})
_UUID = re.compile(
    r"^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$", re.I
)
_TIMESTAMP = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:?\d{2})$")
_REFERENCE = re.compile(r"^\{\{([a-zA-Z][a-zA-Z0-9_-]*)\.([a-zA-Z][a-zA-Z0-9_-]*)\}\}$")
_REFERENCE_ANY = re.compile(r"\{\{([a-zA-Z][a-zA-Z0-9_-]*)\.([a-zA-Z][a-zA-Z0-9_-]*)\}\}")
_HTTP_METHODS = frozenset({"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"})


@dataclass(frozen=True)
class Response:
    status: int
    headers: dict[str, str]
    body: Any


@dataclass(frozen=True)
class Difference:
    path: str
    official: Any
    graphharbor: Any


def normalize(value: Any, *, key: str | None = None) -> Any:
    """Remove only documented values that cannot match across two services."""
    if key in _DYNAMIC_KEYS:
        return "<timestamp>"
    if key in {"content-location", "location"}:
        return "<location>"
    if isinstance(value, dict):
        return {str(name): normalize(item, key=str(name)) for name, item in sorted(value.items())}
    if isinstance(value, list):
        return [normalize(item) for item in value]
    if isinstance(value, str):
        if _UUID.fullmatch(value):
            return "<uuid>"
        if _TIMESTAMP.fullmatch(value):
            return "<timestamp>"
    return value


def _differences(official: Any, graphharbor: Any, path: str = "$") -> list[Difference]:
    if type(official) is not type(graphharbor):
        return [Difference(path, official, graphharbor)]
    if isinstance(official, dict):
        differences: list[Difference] = []
        for key in sorted(set(official) | set(graphharbor)):
            child = f"{path}.{key}"
            if key not in official:
                differences.append(Difference(child, "<missing>", graphharbor[key]))
            elif key not in graphharbor:
                differences.append(Difference(child, official[key], "<missing>"))
            else:
                differences.extend(_differences(official[key], graphharbor[key], child))
        return differences
    if isinstance(official, list):
        differences = []
        for index, (left, right) in enumerate(zip(official, graphharbor, strict=False)):
            differences.extend(_differences(left, right, f"{path}[{index}]"))
        if len(official) != len(graphharbor):
            differences.append(Difference(f"{path}.length", len(official), len(graphharbor)))
        return differences
    return [] if official == graphharbor else [Difference(path, official, graphharbor)]


def _normalize_sse(body: Any) -> Any:
    if not isinstance(body, str):
        return body
    frames: list[tuple[tuple[str, str], ...]] = []
    for frame in body.replace("\r\n", "\n").split("\n\n"):
        lines: list[tuple[str, str]] = []
        for line in frame.splitlines():
            name, _, value = line.partition(":")
            if name == "id":
                continue
            if name == "data":
                try:
                    value = json.dumps(normalize(json.loads(value.lstrip())), separators=(",", ":"))
                except json.JSONDecodeError:
                    pass
            if name:
                lines.append((name, value.lstrip()))
        if lines:
            frames.append(tuple(lines))
    return frames


def compare(official: Response, graphharbor: Response, *, path: str) -> list[Difference]:
    differences = _differences(official.status, graphharbor.status, f"{path}.status")
    for header in ("content-type", "content-location", "location"):
        differences.extend(
            _differences(
                normalize(official.headers.get(header), key=header),
                normalize(graphharbor.headers.get(header), key=header),
                f"{path}.headers.{header}",
            )
        )
    if path == "/openapi.json":
        # OpenAPI operation metadata is generated by different frameworks and
        # is not the compatibility contract. Compare path/method availability
        # below, while the HTTP status and media type remain strict.
        return differences
    if official.headers.get("content-type") == "text/event-stream":
        official_body = _normalize_sse(official.body)
        graphharbor_body = _normalize_sse(graphharbor.body)
    else:
        official_body = normalize(official.body)
        graphharbor_body = normalize(graphharbor.body)
    return differences + _differences(official_body, graphharbor_body, f"{path}.body")


def _request(
    base_url: str, method: str, path: str, timeout: float, body: Any | None = None
) -> Response:
    data = json.dumps(body).encode("utf-8") if body is not None else None
    request = Request(
        f"{base_url.rstrip('/')}{path}",
        data=data,
        headers={"content-type": "application/json"} if data is not None else {},
        method=method,
    )
    try:
        response = urlopen(request, timeout=timeout)
    except HTTPError as error:
        response = error
    raw = response.read().decode("utf-8")
    try:
        body = json.loads(raw) if raw else None
    except json.JSONDecodeError:
        body = raw
    return Response(
        status=response.status,
        headers={key.lower(): value.split(";", 1)[0] for key, value in response.headers.items()},
        body=body,
    )


def _parse_probe(value: str) -> tuple[str, str]:
    method, separator, path = value.partition(":")
    if not separator or method != "GET" or not path.startswith("/"):
        raise ValueError(f"invalid probe {value!r}; expected GET:/path")
    return method, path


def _resolve_references(value: Any, responses: dict[str, Any]) -> Any:
    if isinstance(value, dict):
        return {key: _resolve_references(item, responses) for key, item in value.items()}
    if isinstance(value, list):
        return [_resolve_references(item, responses) for item in value]
    if not isinstance(value, str):
        return value
    match = _REFERENCE.fullmatch(value)
    if match:
        step, field = match.groups()
        response = responses.get(step)
        if not isinstance(response, dict) or field not in response:
            raise ValueError(f"reference {value!r} has no JSON response field")
        return response[field]

    def replace(match: re.Match[str]) -> str:
        step, field = match.groups()
        response = responses.get(step)
        if not isinstance(response, dict) or field not in response:
            raise ValueError(f"reference {match.group()!r} has no JSON response field")
        return str(response[field])

    return _REFERENCE_ANY.sub(replace, value)


def _load_scenario(path: str) -> list[dict[str, Any]]:
    value = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(value, list):
        raise ValueError("scenario must be a JSON array")
    steps: list[dict[str, Any]] = []
    names: set[str] = set()
    for index, raw in enumerate(value, start=1):
        if not isinstance(raw, dict):
            raise ValueError(f"scenario step {index} must be an object")
        name = raw.get("name")
        method = raw.get("method")
        request_path = raw.get("path")
        if not isinstance(name, str) or not _REFERENCE.match(f"{{{{{name}.field}}}}") or name in names:
            raise ValueError(f"scenario step {index} needs a unique identifier name")
        if not isinstance(method, str) or method.upper() not in _HTTP_METHODS:
            raise ValueError(f"scenario step {name!r} has an invalid HTTP method")
        if not isinstance(request_path, str) or not request_path.startswith("/"):
            raise ValueError(f"scenario step {name!r} needs an absolute request path")
        steps.append({"name": name, "method": method.upper(), "path": request_path, "body": raw.get("body")})
        names.add(name)
    return steps


_OPENAPI_METHODS = frozenset({"get", "post", "put", "patch", "delete", "head", "options"})


def _compare_openapi(
    official: Response,
    graphharbor: Response,
    ignored_paths: set[str],
    ignored_methods: set[tuple[str, str]] | None = None,
) -> list[Difference]:
    if not isinstance(official.body, dict) or not isinstance(graphharbor.body, dict):
        return []
    left = official.body.get("paths")
    right = graphharbor.body.get("paths")
    if not isinstance(left, dict) or not isinstance(right, dict):
        return []
    ignored_methods = ignored_methods or set()
    official_paths = {
        path: sorted(
            method
            for method in value
            if method in _OPENAPI_METHODS and (path, method.upper()) not in ignored_methods
        )
        for path, value in left.items()
        if path not in ignored_paths and isinstance(value, dict)
    }
    graphharbor_paths = {
        path: sorted(
            method
            for method in value
            if method in _OPENAPI_METHODS and (path, method.upper()) not in ignored_methods
        )
        for path, value in right.items()
        if path not in ignored_paths and isinstance(value, dict)
    }
    return _differences(official_paths, graphharbor_paths, "$.openapi.paths")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--official-url", required=True, help="fixed-version official Agent Server URL"
    )
    parser.add_argument("--graphharbor-url", required=True, help="GraphHarbor Agent Server URL")
    parser.add_argument("--probe", action="append", default=[], help="additional GET:/path probe")
    parser.add_argument(
        "--sse-path",
        action="append",
        default=[],
        help="GET stream path whose event sequence and payload must match",
    )
    parser.add_argument(
        "--ignore-openapi-path",
        action="append",
        default=[],
        help="documented unsupported official path to exclude",
    )
    parser.add_argument(
        "--ignore-openapi-method",
        action="append",
        default=[],
        help="documented compatibility method exclusion, formatted /path:METHOD",
    )
    parser.add_argument(
        "--scenario",
        help="JSON request sequence with per-service response references",
    )
    parser.add_argument("--timeout", type=float, default=15.0)
    args = parser.parse_args()

    ignored_methods: set[tuple[str, str]] = set()
    for value in args.ignore_openapi_method:
        path, separator, method = value.rpartition(":")
        if not separator or not path.startswith("/") or method.lower() not in _OPENAPI_METHODS:
            parser.error(f"invalid OpenAPI method exclusion {value!r}; expected /path:METHOD")
        ignored_methods.add((path, method.upper()))

    differences: list[Difference] = []
    for probe in [*DEFAULT_PROBES, *args.probe]:
        try:
            method, path = _parse_probe(probe)
        except ValueError as error:
            parser.error(str(error))
        official = _request(args.official_url, method, path, args.timeout)
        graphharbor = _request(args.graphharbor_url, method, path, args.timeout)
        differences.extend(compare(official, graphharbor, path=path))
        if path == "/openapi.json":
            differences.extend(
                _compare_openapi(
                    official,
                    graphharbor,
                    set(args.ignore_openapi_path),
                    ignored_methods,
                )
            )
    for path in args.sse_path:
        if not path.startswith("/"):
            parser.error(f"invalid SSE path {path!r}; expected /path")
        official = _request(args.official_url, "GET", path, args.timeout)
        graphharbor = _request(args.graphharbor_url, "GET", path, args.timeout)
        differences.extend(compare(official, graphharbor, path=path))

    if args.scenario:
        try:
            steps = _load_scenario(args.scenario)
        except (OSError, ValueError, json.JSONDecodeError) as error:
            parser.error(f"invalid scenario: {error}")
        official_responses: dict[str, Any] = {}
        graphharbor_responses: dict[str, Any] = {}
        for step in steps:
            try:
                official_path = _resolve_references(step["path"], official_responses)
                graphharbor_path = _resolve_references(step["path"], graphharbor_responses)
                official_body = _resolve_references(step["body"], official_responses)
                graphharbor_body = _resolve_references(step["body"], graphharbor_responses)
            except ValueError as error:
                parser.error(f"invalid scenario step {step['name']!r}: {error}")
            official = _request(
                args.official_url, step["method"], official_path, args.timeout, official_body
            )
            graphharbor = _request(
                args.graphharbor_url,
                step["method"],
                graphharbor_path,
                args.timeout,
                graphharbor_body,
            )
            differences.extend(compare(official, graphharbor, path=f"scenario.{step['name']}"))
            official_responses[step["name"]] = official.body
            graphharbor_responses[step["name"]] = graphharbor.body

    if not differences:
        sys.stdout.write("official protocol comparison: OK\n")
        return 0
    sys.stderr.write("official protocol comparison: FAIL\n")
    for difference in differences:
        sys.stderr.write(
            f"- {difference.path}: official={difference.official!r} "
            f"graphharbor={difference.graphharbor!r}\n"
        )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
